name: integration

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - main

env:
  ENV: testing
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Setup uv and Python
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: latest

    - name: Setup Snowflake CLI
      uses: snowflakedb/snowflake-cli-action@v2.0
      with:
        use-oidc: true

    - name: Setup Snowflake Connection
      run: |
        echo UV_PYTHON="3.12" > $GITHUB_ENV
        mkdir -p ~/.snowflake
        cat > ~/.snowflake/connections.toml <<EOF
        [default]
        account = "${SNOWFLAKE_ACCOUNT}"
        authenticator = "${SNOWFLAKE_AUTHENTICATOR}"
        workload_identity_provider = "${SNOWFLAKE_WORKLOAD_IDENTITY_PROVIDER}"
        token = "${SNOWFLAKE_TOKEN}"
        warehouse = "COMPUTE_WH"
        database = "DEFAULT"
        schema = "DEV"
        role = "ICEBERG_MCP_DATA"
        EOF

    - name: Run Tests
      run: uv run pytest --cov src --cov-report xml:coverage.xml

    - name: Lint Project and Formatting
      run: |
        uv run ruff check
        uv run ruff format --check
        uv run ty check

    - name: Upload Coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml

  analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: python

    - name: AutoBuild
      uses: github/codeql-action/autobuild@v4

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: /language:python